# Generated by Django 5.0.7 on 2024-09-12 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_remove_product_purchased_product_stock_bid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auctionproduct',
            name='purchased',
        ),
    ]
