# Generated by Django 5.0.7 on 2024-09-09 10:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_rename_default_county_userprofile_billing_county_and_more'),
        ('store', '0002_remove_product_purchased_product_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuctionProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auction_id', models.CharField(blank=True, max_length=254, null=True)),
                ('title', models.CharField(max_length=254)),
                ('description', models.TextField()),
                ('image_url', models.URLField(blank=True, max_length=1024, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('condition', models.CharField(choices=[('new', 'New / Never Opened'), ('refurbished', 'Refurbished'), ('mint_condition', 'Mint Condition'), ('good_condition', 'Good Condition'), ('poor_condition', 'Poor Condition')], max_length=20)),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('auction_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('auction_period', models.DecimalField(decimal_places=0, max_digits=6)),
                ('purchased', models.BooleanField(blank=True, default=False, null=True)),
                ('seller', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auction', to='profiles.userprofile')),
            ],
            options={
                'verbose_name_plural': 'Auctions',
            },
        ),
        migrations.CreateModel(
            name='RentalProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rental_sku', models.CharField(blank=True, max_length=254, null=True)),
                ('rental_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('rental_period', models.DateField()),
                ('rental_stock', models.DecimalField(decimal_places=0, default=0, max_digits=6)),
                ('has_premium', models.BooleanField(blank=True, default=False, null=True)),
                ('premium', models.BooleanField(blank=True, default=False, null=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.product')),
            ],
            options={
                'verbose_name_plural': 'Rentals',
            },
        ),
    ]
