# Generated by Django 5.0.7 on 2024-09-10 13:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_rename_default_county_userprofile_billing_county_and_more'),
        ('store', '0003_auctionproduct_rentalproduct'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auctionproduct',
            name='auction_id',
        ),
        migrations.RemoveField(
            model_name='auctionproduct',
            name='auction_price',
        ),
        migrations.AlterField(
            model_name='auctionproduct',
            name='seller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auction_seller', to='profiles.userprofile'),
        ),
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('buyer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auction_buyer', to='profiles.userprofile')),
            ],
        ),
        migrations.AddField(
            model_name='auctionproduct',
            name='bidders',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bid', to='store.bid'),
        ),
    ]
