# Generated by Django 5.0.7 on 2024-09-13 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_auctionproduct_bidders_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auctionproduct',
            name='seller',
        ),
    ]
