# Generated by Django 5.0.7 on 2024-09-12 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_remove_auctionproduct_purchased'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionproduct',
            name='purchased',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
