# Generated by Django 5.0.7 on 2024-09-11 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_remove_auctionproduct_auction_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionproduct',
            name='instrument',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='bid',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
