# Generated by Django 5.0.7 on 2024-09-11 08:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_auctionproduct_instrument'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionproduct',
            name='bidders',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bid', to='store.bid'),
        ),
    ]
