# Generated by Django 5.0.7 on 2024-09-11 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_auctionproduct_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionproduct',
            name='auction_period',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
