# Generated by Django 5.0.7 on 2024-09-11 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_alter_auctionproduct_auction_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionproduct',
            name='auction_period',
            field=models.DateField(),
        ),
    ]
