# Generated by Django 5.0.7 on 2024-09-06 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20)),
                ('subject', models.CharField(choices=[('general', 'General Enquiry'), ('return', 'Product Return'), ('auction', 'Auction Enquiry'), ('rental', 'Rental Enquiry'), ('career', 'Career Interest')], default='general', max_length=20)),
                ('message', models.CharField(default='', max_length=80)),
                ('signup', models.BooleanField(default=False, max_length=80)),
            ],
        ),
    ]
