# Generated by Django 5.0.7 on 2024-09-09 10:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='create_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='signup',
            field=models.BooleanField(default=False, max_length=1),
        ),
    ]
