# Generated by Django 5.0.7 on 2024-09-09 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_enquiry_create_date_alter_enquiry_signup'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='enquiry',
            options={'verbose_name_plural': 'Enquiries'},
        ),
    ]
