# Generated by Django 5.0.7 on 2024-09-12 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_enquiry_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='enquiry_number',
            field=models.CharField(default='000000', editable=False, max_length=32),
        ),
    ]
